### ISSUE TITLE
The form editor randomly changes the json into yaml

### ISSUE THREAD

**Issue by jhordies** [apigitlabs/apigit-support#14] opened 2023-03-31 10:48 UTC
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

While editing a json specification,
when using the form editor (to simply add a summary to an operation) if I open the code editor, it became a yaml file

### Steps To Reproduce

While editing a json specification,
when using the form editor (to simply add a summary to an operation) if I open the code editor, it became a yaml file

### Browser

Chrome

**Comment by apigitlabs** [comment] 2023-04-04 23:47
Thank you for your input, @jhordies. After investigating the issue further, we suspect that the JSON in the original specification may have been broken, causing it to be mistakenly interpreted as YAML. We will attempt to reproduce the issue and provide an update as soon as possible.

**Comment by apigitlabs** [comment] 2023-04-10 18:40
@jhordies , we can't reproduce it locally, but made some improvement to avoid this case. Can you help to double check and see if it is fixed ?

**Comment by jhordies** [comment] 2023-04-11 07:04
Hi, thanks, it seems fixed.

**Comment by apigitlabs** [comment] 2023-04-11 20:53
thanks @jhordies for the confirmation , I will close this issue first.

**Closed by apigitlabs** 2023-04-11 20:53 UTC
